version: '3.3'

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  a2e-lake-assets:

services:
  assets:
    image: mullenkamp/a2e-lake-scenario-app-assets:1.1
    volumes:
      - a2e-lake-assets:/app/assets
    networks:
      - net
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.function == web_server

  dash:
    image: mullenkamp/a2e-lake-scenario-app:1.0
    volumes:
      - a2e-lake-assets:/app/assets
    networks:
      # - net
      - traefik-public
    depends_on:
      - assets
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.function == web_server
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.a2e-lake-app-http.rule=Host(`web-app3.monitoringfreshwater.co.nz`)
        - traefik.http.routers.a2e-lake-app-http.entrypoints=http
        - traefik.http.routers.a2e-lake-app-http.middlewares=https-redirect
        - traefik.http.routers.a2e-lake-app-https.rule=Host(`web-app3.monitoringfreshwater.co.nz`)
        - traefik.http.routers.a2e-lake-app-https.entrypoints=https
        - traefik.http.routers.a2e-lake-app-https.tls=true
        # - traefik.http.routers.es-dash-https.tls.certresolver=le
        - traefik.http.services.a2e-lake-app.loadbalancer.server.port=80
