version: '3.3'

networks:
  net:
    # driver: overlay
    attachable: true

volumes:
  a2e-lake-assets:

services:
  assets:
    image: mullenkamp/a2e-lake-scenario-app-assets:1.3
    volumes:
      - a2e-lake-assets:/app/assets
    networks:
      - net
    deploy:
      restart_policy:
        condition: none

  a2e-lake-app:
    image: mullenkamp/a2e-lake-scenario-app:1.3
    volumes:
      - a2e-lake-assets:/app/assets
    networks:
      - net
    depends_on:
      - assets
    ports:
      - "8000:80"
