version: '3.3'

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  a2e-lake-assets-test:
    # driver: vieux/sshfs
    # driver_opts:
    #   sshcmd: app@olw-aus2.nzrivers.xyz:/mnt/app_data/a2e-lake-assets
    #   password: app4u

services:
  assets:
    image: mullenkamp/a2e-lake-scenario-app-assets:1.3
    volumes:
      - a2e-lake-assets-test:/app/assets
    networks:
      - net
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          # - node.labels.function == web_server
          - node.hostname == olw-aus2.nzrivers.xyz

  dash:
    image: mullenkamp/a2e-lake-scenario-app:1.4.1
    volumes:
      - a2e-lake-assets-test:/app/assets
    networks:
      # - net
      - traefik-public
    depends_on:
      - assets
    deploy:
      replicas: 1
      placement:
        constraints:
          # - node.labels.function == web_server
          - node.hostname == olw-aus2.nzrivers.xyz
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.olw-app-base-test-http.rule=Host(`test.monitoringfreshwater.co.nz`)
        - traefik.http.routers.olw-app-base-test-http.entrypoints=http
        - traefik.http.routers.olw-app-base-test-http.middlewares=https-redirect
        - traefik.http.routers.olw-app-base-test-https.rule=Host(`test.monitoringfreshwater.co.nz`)
        - traefik.http.routers.olw-app-base-test-https.entrypoints=https
        - traefik.http.routers.olw-app-base-test-https.tls=true
        # - traefik.http.routers.es-dash-https.tls.certresolver=le
        - traefik.http.services.olw-app-base-test.loadbalancer.server.port=80
